// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/v1/login": {
            "post": {
                "description": "Проверяет email/пароль и возвращает пару access/refresh токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логин пользователя",
                "parameters": [
                    {
                        "description": "Учётные данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь заблокирован",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/logout": {
            "post": {
                "description": "Помечает переданный refresh-токен как отозванный. Идемпотентен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логаут с одного устройства",
                "parameters": [
                    {
                        "description": "Refresh токен (опционально)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешный логаут, тело отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/password/reset/confirm": {
            "post": {
                "description": "Проверяет OTP-код, устанавливает новый пароль и инвалидирует все refresh-токены пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "password-reset"
                ],
                "summary": "Подтверждение сброса пароля",
                "parameters": [
                    {
                        "description": "Email, OTP-код и новый пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ConfirmResetRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пароль успешно изменён, тело отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный код или некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/password/reset/start": {
            "post": {
                "description": "Генерирует одноразовый код для сброса пароля и сохраняет его. В dev-режиме возвращает код в ответе.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "password-reset"
                ],
                "summary": "Начало сброса пароля",
                "parameters": [
                    {
                        "description": "Email пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.StartResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dev-режим: OTP-код в ответе",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.StartResetDevResponse"
                        }
                    },
                    "204": {
                        "description": "В проде: всегда 204, даже если email не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/refresh": {
            "post": {
                "description": "Принимает refresh-токен и возвращает новую пару access/refresh (rotation)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или просроченный refresh-токен",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/register": {
            "post": {
                "description": "Создаёт нового пользователя и возвращает пару access/refresh токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Учётные данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь с таким email уже существует",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/v1/validate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Проверяет access-токен, убеждается что пользователь существует и не заблокирован, и возвращает его ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Валидация access-токена",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer access токен",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ValidateResponse"
                        }
                    },
                    "401": {
                        "description": "Нет токена или он невалиден",
                        "schema": {
                            "$ref": "#/definitions/auth_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth_internal_adapter_in_http_dto.ConfirmResetRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.StartResetDevResponse": {
            "type": "object",
            "properties": {
                "dev_code": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.StartResetRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth_internal_adapter_in_http_dto.ValidateResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Enduran Auth API",
	Description:      "Сервис аутентификации Enduran (регистрация, логин, refresh, сброс пароля)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
